# Generated by Django 5.2.1 on 2025-05-15 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0001_initial'),
        ('users', '0002_user_phone_delete_clientprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('fkBusiness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.businessprofile')),
                ('fkClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fkService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.service')),
            ],
        ),
    ]
