# Generated by Django 5.2.1 on 2025-05-15 14:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_phone_delete_clientprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(5)])),
                ('description', models.TextField(max_length=300)),
                ('duration', models.DurationField()),
                ('fkBusiness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.businessprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CommentsOnService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('fkClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fkService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.service')),
            ],
        ),
    ]
